spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://192.168.30.113/sell?characterEncoding=utf-8&useSSL=false&&serverTimezone=UTC
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 122.51.89.36
    port: 6379
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: E:/vm/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: 4Ysj7aeIO72_egI8Eo1S2XpE5v6GQLh5V0NOB0lu6rQ

projectUrl:
  wechatMpAuthorize: http://sell.natapp4.cc
  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://sell.natapp4.cc
logging:
  level:
    com.imooc.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 又拍云服务 见 https://console.upyun.com/services/file/
upyun:
  bucketName: XXX
  userName: xxx
  password: xxxx
  imageHost: http://xxx.com/
server:
  servlet:
    context-path: /sell